services:
  box:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "9443:443"
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - CLI_BOX_DEBUG=${CLI_BOX_DEBUG-}
    volumes:
      - state:/work/state
      - secure:/work/secure
    restart: unless-stopped

volumes:
  state:
  secure:
