// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: proto/clibox.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FileAttr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ino           uint64                 `protobuf:"varint,1,opt,name=ino,proto3" json:"ino,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Nlink         uint32                 `protobuf:"varint,4,opt,name=nlink,proto3" json:"nlink,omitempty"`
	Uid           uint32                 `protobuf:"varint,5,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,6,opt,name=gid,proto3" json:"gid,omitempty"`
	AtimeSec      int64                  `protobuf:"varint,7,opt,name=atime_sec,json=atimeSec,proto3" json:"atime_sec,omitempty"`
	MtimeSec      int64                  `protobuf:"varint,8,opt,name=mtime_sec,json=mtimeSec,proto3" json:"mtime_sec,omitempty"`
	CtimeSec      int64                  `protobuf:"varint,9,opt,name=ctime_sec,json=ctimeSec,proto3" json:"ctime_sec,omitempty"`
	AtimeNsec     int32                  `protobuf:"varint,10,opt,name=atime_nsec,json=atimeNsec,proto3" json:"atime_nsec,omitempty"`
	MtimeNsec     int32                  `protobuf:"varint,11,opt,name=mtime_nsec,json=mtimeNsec,proto3" json:"mtime_nsec,omitempty"`
	CtimeNsec     int32                  `protobuf:"varint,12,opt,name=ctime_nsec,json=ctimeNsec,proto3" json:"ctime_nsec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAttr) Reset() {
	*x = FileAttr{}
	mi := &file_proto_clibox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAttr) ProtoMessage() {}

func (x *FileAttr) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAttr.ProtoReflect.Descriptor instead.
func (*FileAttr) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{0}
}

func (x *FileAttr) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *FileAttr) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *FileAttr) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *FileAttr) GetNlink() uint32 {
	if x != nil {
		return x.Nlink
	}
	return 0
}

func (x *FileAttr) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *FileAttr) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

func (x *FileAttr) GetAtimeSec() int64 {
	if x != nil {
		return x.AtimeSec
	}
	return 0
}

func (x *FileAttr) GetMtimeSec() int64 {
	if x != nil {
		return x.MtimeSec
	}
	return 0
}

func (x *FileAttr) GetCtimeSec() int64 {
	if x != nil {
		return x.CtimeSec
	}
	return 0
}

func (x *FileAttr) GetAtimeNsec() int32 {
	if x != nil {
		return x.AtimeNsec
	}
	return 0
}

func (x *FileAttr) GetMtimeNsec() int32 {
	if x != nil {
		return x.MtimeNsec
	}
	return 0
}

func (x *FileAttr) GetCtimeNsec() int32 {
	if x != nil {
		return x.CtimeNsec
	}
	return 0
}

type DirEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ino           uint64                 `protobuf:"varint,2,opt,name=ino,proto3" json:"ino,omitempty"`
	Mode          uint32                 `protobuf:"varint,3,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DirEntry) Reset() {
	*x = DirEntry{}
	mi := &file_proto_clibox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirEntry) ProtoMessage() {}

func (x *DirEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirEntry.ProtoReflect.Descriptor instead.
func (*DirEntry) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{1}
}

func (x *DirEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DirEntry) GetIno() uint64 {
	if x != nil {
		return x.Ino
	}
	return 0
}

func (x *DirEntry) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type GetAttrRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrRequest) Reset() {
	*x = GetAttrRequest{}
	mi := &file_proto_clibox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrRequest) ProtoMessage() {}

func (x *GetAttrRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrRequest.ProtoReflect.Descriptor instead.
func (*GetAttrRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{2}
}

func (x *GetAttrRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type GetAttrResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Attr          *FileAttr              `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttrResponse) Reset() {
	*x = GetAttrResponse{}
	mi := &file_proto_clibox_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttrResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttrResponse) ProtoMessage() {}

func (x *GetAttrResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttrResponse.ProtoReflect.Descriptor instead.
func (*GetAttrResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{3}
}

func (x *GetAttrResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *GetAttrResponse) GetAttr() *FileAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_proto_clibox_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{4}
}

func (x *LookupRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *LookupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Attr          *FileAttr              `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_proto_clibox_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{5}
}

func (x *LookupResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *LookupResponse) GetAttr() *FileAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type ReadLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLinkRequest) Reset() {
	*x = ReadLinkRequest{}
	mi := &file_proto_clibox_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLinkRequest) ProtoMessage() {}

func (x *ReadLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLinkRequest.ProtoReflect.Descriptor instead.
func (*ReadLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{6}
}

func (x *ReadLinkRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type ReadLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Target        string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadLinkResponse) Reset() {
	*x = ReadLinkResponse{}
	mi := &file_proto_clibox_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadLinkResponse) ProtoMessage() {}

func (x *ReadLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadLinkResponse.ProtoReflect.Descriptor instead.
func (*ReadLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{7}
}

func (x *ReadLinkResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *ReadLinkResponse) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type OpenDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenDirRequest) Reset() {
	*x = OpenDirRequest{}
	mi := &file_proto_clibox_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDirRequest) ProtoMessage() {}

func (x *OpenDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDirRequest.ProtoReflect.Descriptor instead.
func (*OpenDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{8}
}

func (x *OpenDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type OpenDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Fh            uint64                 `protobuf:"varint,2,opt,name=fh,proto3" json:"fh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenDirResponse) Reset() {
	*x = OpenDirResponse{}
	mi := &file_proto_clibox_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenDirResponse) ProtoMessage() {}

func (x *OpenDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenDirResponse.ProtoReflect.Descriptor instead.
func (*OpenDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{9}
}

func (x *OpenDirResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *OpenDirResponse) GetFh() uint64 {
	if x != nil {
		return x.Fh
	}
	return 0
}

type ReadDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Fh            uint64                 `protobuf:"varint,2,opt,name=fh,proto3" json:"fh,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirRequest) Reset() {
	*x = ReadDirRequest{}
	mi := &file_proto_clibox_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirRequest) ProtoMessage() {}

func (x *ReadDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirRequest.ProtoReflect.Descriptor instead.
func (*ReadDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{10}
}

func (x *ReadDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadDirRequest) GetFh() uint64 {
	if x != nil {
		return x.Fh
	}
	return 0
}

func (x *ReadDirRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Entries       []*DirEntry            `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadDirResponse) Reset() {
	*x = ReadDirResponse{}
	mi := &file_proto_clibox_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadDirResponse) ProtoMessage() {}

func (x *ReadDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadDirResponse.ProtoReflect.Descriptor instead.
func (*ReadDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{11}
}

func (x *ReadDirResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *ReadDirResponse) GetEntries() []*DirEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ReleaseDirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Fh            uint64                 `protobuf:"varint,2,opt,name=fh,proto3" json:"fh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseDirRequest) Reset() {
	*x = ReleaseDirRequest{}
	mi := &file_proto_clibox_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseDirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseDirRequest) ProtoMessage() {}

func (x *ReleaseDirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseDirRequest.ProtoReflect.Descriptor instead.
func (*ReleaseDirRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{12}
}

func (x *ReleaseDirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReleaseDirRequest) GetFh() uint64 {
	if x != nil {
		return x.Fh
	}
	return 0
}

type ReleaseDirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseDirResponse) Reset() {
	*x = ReleaseDirResponse{}
	mi := &file_proto_clibox_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseDirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseDirResponse) ProtoMessage() {}

func (x *ReleaseDirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseDirResponse.ProtoReflect.Descriptor instead.
func (*ReleaseDirResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{13}
}

func (x *ReleaseDirResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type MkdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirRequest) Reset() {
	*x = MkdirRequest{}
	mi := &file_proto_clibox_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirRequest) ProtoMessage() {}

func (x *MkdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirRequest.ProtoReflect.Descriptor instead.
func (*MkdirRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{14}
}

func (x *MkdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *MkdirRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type MkdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Attr          *FileAttr              `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MkdirResponse) Reset() {
	*x = MkdirResponse{}
	mi := &file_proto_clibox_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MkdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MkdirResponse) ProtoMessage() {}

func (x *MkdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MkdirResponse.ProtoReflect.Descriptor instead.
func (*MkdirResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{15}
}

func (x *MkdirResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *MkdirResponse) GetAttr() *FileAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type RmdirRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmdirRequest) Reset() {
	*x = RmdirRequest{}
	mi := &file_proto_clibox_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmdirRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmdirRequest) ProtoMessage() {}

func (x *RmdirRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmdirRequest.ProtoReflect.Descriptor instead.
func (*RmdirRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{16}
}

func (x *RmdirRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type RmdirResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RmdirResponse) Reset() {
	*x = RmdirResponse{}
	mi := &file_proto_clibox_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RmdirResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RmdirResponse) ProtoMessage() {}

func (x *RmdirResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RmdirResponse.ProtoReflect.Descriptor instead.
func (*RmdirResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{17}
}

func (x *RmdirResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type OpenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Flags         uint32                 `protobuf:"varint,2,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenRequest) Reset() {
	*x = OpenRequest{}
	mi := &file_proto_clibox_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenRequest) ProtoMessage() {}

func (x *OpenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenRequest.ProtoReflect.Descriptor instead.
func (*OpenRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{18}
}

func (x *OpenRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *OpenRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type OpenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Fh            uint64                 `protobuf:"varint,2,opt,name=fh,proto3" json:"fh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenResponse) Reset() {
	*x = OpenResponse{}
	mi := &file_proto_clibox_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenResponse) ProtoMessage() {}

func (x *OpenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenResponse.ProtoReflect.Descriptor instead.
func (*OpenResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{19}
}

func (x *OpenResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *OpenResponse) GetFh() uint64 {
	if x != nil {
		return x.Fh
	}
	return 0
}

type ReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Fh            uint64                 `protobuf:"varint,2,opt,name=fh,proto3" json:"fh,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Size          uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_proto_clibox_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{20}
}

func (x *ReadRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReadRequest) GetFh() uint64 {
	if x != nil {
		return x.Fh
	}
	return 0
}

func (x *ReadRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ReadRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_proto_clibox_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{21}
}

func (x *ReadResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *ReadResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Fh            uint64                 `protobuf:"varint,2,opt,name=fh,proto3" json:"fh,omitempty"`
	Offset        int64                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	Data          []byte                 `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteRequest) Reset() {
	*x = WriteRequest{}
	mi := &file_proto_clibox_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteRequest) ProtoMessage() {}

func (x *WriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteRequest.ProtoReflect.Descriptor instead.
func (*WriteRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{22}
}

func (x *WriteRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *WriteRequest) GetFh() uint64 {
	if x != nil {
		return x.Fh
	}
	return 0
}

func (x *WriteRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WriteRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Written       uint32                 `protobuf:"varint,2,opt,name=written,proto3" json:"written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteResponse) Reset() {
	*x = WriteResponse{}
	mi := &file_proto_clibox_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteResponse) ProtoMessage() {}

func (x *WriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteResponse.ProtoReflect.Descriptor instead.
func (*WriteResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{23}
}

func (x *WriteResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *WriteResponse) GetWritten() uint32 {
	if x != nil {
		return x.Written
	}
	return 0
}

type ReleaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Fh            uint64                 `protobuf:"varint,2,opt,name=fh,proto3" json:"fh,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_proto_clibox_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{24}
}

func (x *ReleaseRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ReleaseRequest) GetFh() uint64 {
	if x != nil {
		return x.Fh
	}
	return 0
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_proto_clibox_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{25}
}

func (x *ReleaseResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Flags         uint32                 `protobuf:"varint,3,opt,name=flags,proto3" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_proto_clibox_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{26}
}

func (x *CreateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *CreateRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *CreateRequest) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Fh            uint64                 `protobuf:"varint,2,opt,name=fh,proto3" json:"fh,omitempty"`
	Attr          *FileAttr              `protobuf:"bytes,3,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_proto_clibox_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{27}
}

func (x *CreateResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *CreateResponse) GetFh() uint64 {
	if x != nil {
		return x.Fh
	}
	return 0
}

func (x *CreateResponse) GetAttr() *FileAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type UnlinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkRequest) Reset() {
	*x = UnlinkRequest{}
	mi := &file_proto_clibox_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkRequest) ProtoMessage() {}

func (x *UnlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkRequest.ProtoReflect.Descriptor instead.
func (*UnlinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{28}
}

func (x *UnlinkRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type UnlinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkResponse) Reset() {
	*x = UnlinkResponse{}
	mi := &file_proto_clibox_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkResponse) ProtoMessage() {}

func (x *UnlinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkResponse.ProtoReflect.Descriptor instead.
func (*UnlinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{29}
}

func (x *UnlinkResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type RenameRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameRequest) Reset() {
	*x = RenameRequest{}
	mi := &file_proto_clibox_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameRequest) ProtoMessage() {}

func (x *RenameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameRequest.ProtoReflect.Descriptor instead.
func (*RenameRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{30}
}

func (x *RenameRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *RenameRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type RenameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenameResponse) Reset() {
	*x = RenameResponse{}
	mi := &file_proto_clibox_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameResponse) ProtoMessage() {}

func (x *RenameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameResponse.ProtoReflect.Descriptor instead.
func (*RenameResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{31}
}

func (x *RenameResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type TruncateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Size          int64                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateRequest) Reset() {
	*x = TruncateRequest{}
	mi := &file_proto_clibox_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateRequest) ProtoMessage() {}

func (x *TruncateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateRequest.ProtoReflect.Descriptor instead.
func (*TruncateRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{32}
}

func (x *TruncateRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *TruncateRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type TruncateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TruncateResponse) Reset() {
	*x = TruncateResponse{}
	mi := &file_proto_clibox_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TruncateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TruncateResponse) ProtoMessage() {}

func (x *TruncateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TruncateResponse.ProtoReflect.Descriptor instead.
func (*TruncateResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{33}
}

func (x *TruncateResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type ChmodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Mode          uint32                 `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodRequest) Reset() {
	*x = ChmodRequest{}
	mi := &file_proto_clibox_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodRequest) ProtoMessage() {}

func (x *ChmodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodRequest.ProtoReflect.Descriptor instead.
func (*ChmodRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{34}
}

func (x *ChmodRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChmodRequest) GetMode() uint32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

type ChmodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChmodResponse) Reset() {
	*x = ChmodResponse{}
	mi := &file_proto_clibox_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChmodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChmodResponse) ProtoMessage() {}

func (x *ChmodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChmodResponse.ProtoReflect.Descriptor instead.
func (*ChmodResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{35}
}

func (x *ChmodResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type ChownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Uid           uint32                 `protobuf:"varint,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Gid           uint32                 `protobuf:"varint,3,opt,name=gid,proto3" json:"gid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChownRequest) Reset() {
	*x = ChownRequest{}
	mi := &file_proto_clibox_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChownRequest) ProtoMessage() {}

func (x *ChownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChownRequest.ProtoReflect.Descriptor instead.
func (*ChownRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{36}
}

func (x *ChownRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ChownRequest) GetUid() uint32 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *ChownRequest) GetGid() uint32 {
	if x != nil {
		return x.Gid
	}
	return 0
}

type ChownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChownResponse) Reset() {
	*x = ChownResponse{}
	mi := &file_proto_clibox_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChownResponse) ProtoMessage() {}

func (x *ChownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChownResponse.ProtoReflect.Descriptor instead.
func (*ChownResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{37}
}

func (x *ChownResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type UtimensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	AtimeSec      int64                  `protobuf:"varint,2,opt,name=atime_sec,json=atimeSec,proto3" json:"atime_sec,omitempty"`
	AtimeNsec     int32                  `protobuf:"varint,3,opt,name=atime_nsec,json=atimeNsec,proto3" json:"atime_nsec,omitempty"`
	MtimeSec      int64                  `protobuf:"varint,4,opt,name=mtime_sec,json=mtimeSec,proto3" json:"mtime_sec,omitempty"`
	MtimeNsec     int32                  `protobuf:"varint,5,opt,name=mtime_nsec,json=mtimeNsec,proto3" json:"mtime_nsec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtimensRequest) Reset() {
	*x = UtimensRequest{}
	mi := &file_proto_clibox_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtimensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtimensRequest) ProtoMessage() {}

func (x *UtimensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtimensRequest.ProtoReflect.Descriptor instead.
func (*UtimensRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{38}
}

func (x *UtimensRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UtimensRequest) GetAtimeSec() int64 {
	if x != nil {
		return x.AtimeSec
	}
	return 0
}

func (x *UtimensRequest) GetAtimeNsec() int32 {
	if x != nil {
		return x.AtimeNsec
	}
	return 0
}

func (x *UtimensRequest) GetMtimeSec() int64 {
	if x != nil {
		return x.MtimeSec
	}
	return 0
}

func (x *UtimensRequest) GetMtimeNsec() int32 {
	if x != nil {
		return x.MtimeNsec
	}
	return 0
}

type UtimensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UtimensResponse) Reset() {
	*x = UtimensResponse{}
	mi := &file_proto_clibox_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UtimensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UtimensResponse) ProtoMessage() {}

func (x *UtimensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UtimensResponse.ProtoReflect.Descriptor instead.
func (*UtimensResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{39}
}

func (x *UtimensResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type SymlinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Target        string                 `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	LinkPath      string                 `protobuf:"bytes,2,opt,name=link_path,json=linkPath,proto3" json:"link_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymlinkRequest) Reset() {
	*x = SymlinkRequest{}
	mi := &file_proto_clibox_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymlinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymlinkRequest) ProtoMessage() {}

func (x *SymlinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymlinkRequest.ProtoReflect.Descriptor instead.
func (*SymlinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{40}
}

func (x *SymlinkRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *SymlinkRequest) GetLinkPath() string {
	if x != nil {
		return x.LinkPath
	}
	return ""
}

type SymlinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Attr          *FileAttr              `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymlinkResponse) Reset() {
	*x = SymlinkResponse{}
	mi := &file_proto_clibox_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymlinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymlinkResponse) ProtoMessage() {}

func (x *SymlinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymlinkResponse.ProtoReflect.Descriptor instead.
func (*SymlinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{41}
}

func (x *SymlinkResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *SymlinkResponse) GetAttr() *FileAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type LinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPath       string                 `protobuf:"bytes,1,opt,name=old_path,json=oldPath,proto3" json:"old_path,omitempty"`
	NewPath       string                 `protobuf:"bytes,2,opt,name=new_path,json=newPath,proto3" json:"new_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkRequest) Reset() {
	*x = LinkRequest{}
	mi := &file_proto_clibox_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkRequest) ProtoMessage() {}

func (x *LinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkRequest.ProtoReflect.Descriptor instead.
func (*LinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{42}
}

func (x *LinkRequest) GetOldPath() string {
	if x != nil {
		return x.OldPath
	}
	return ""
}

func (x *LinkRequest) GetNewPath() string {
	if x != nil {
		return x.NewPath
	}
	return ""
}

type LinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Attr          *FileAttr              `protobuf:"bytes,2,opt,name=attr,proto3" json:"attr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkResponse) Reset() {
	*x = LinkResponse{}
	mi := &file_proto_clibox_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkResponse) ProtoMessage() {}

func (x *LinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkResponse.ProtoReflect.Descriptor instead.
func (*LinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{43}
}

func (x *LinkResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *LinkResponse) GetAttr() *FileAttr {
	if x != nil {
		return x.Attr
	}
	return nil
}

type FsyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Fh            uint64                 `protobuf:"varint,2,opt,name=fh,proto3" json:"fh,omitempty"`
	Datasync      bool                   `protobuf:"varint,3,opt,name=datasync,proto3" json:"datasync,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsyncRequest) Reset() {
	*x = FsyncRequest{}
	mi := &file_proto_clibox_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsyncRequest) ProtoMessage() {}

func (x *FsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsyncRequest.ProtoReflect.Descriptor instead.
func (*FsyncRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{44}
}

func (x *FsyncRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *FsyncRequest) GetFh() uint64 {
	if x != nil {
		return x.Fh
	}
	return 0
}

func (x *FsyncRequest) GetDatasync() bool {
	if x != nil {
		return x.Datasync
	}
	return false
}

type FsyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FsyncResponse) Reset() {
	*x = FsyncResponse{}
	mi := &file_proto_clibox_proto_msgTypes[45]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FsyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FsyncResponse) ProtoMessage() {}

func (x *FsyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[45]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FsyncResponse.ProtoReflect.Descriptor instead.
func (*FsyncResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{45}
}

func (x *FsyncResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

type StatFsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFsRequest) Reset() {
	*x = StatFsRequest{}
	mi := &file_proto_clibox_proto_msgTypes[46]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFsRequest) ProtoMessage() {}

func (x *StatFsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[46]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFsRequest.ProtoReflect.Descriptor instead.
func (*StatFsRequest) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{46}
}

func (x *StatFsRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type StatFsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Errno         int32                  `protobuf:"varint,1,opt,name=errno,proto3" json:"errno,omitempty"`
	Blocks        uint64                 `protobuf:"varint,2,opt,name=blocks,proto3" json:"blocks,omitempty"`
	Bfree         uint64                 `protobuf:"varint,3,opt,name=bfree,proto3" json:"bfree,omitempty"`
	Bavail        uint64                 `protobuf:"varint,4,opt,name=bavail,proto3" json:"bavail,omitempty"`
	Files         uint64                 `protobuf:"varint,5,opt,name=files,proto3" json:"files,omitempty"`
	Ffree         uint64                 `protobuf:"varint,6,opt,name=ffree,proto3" json:"ffree,omitempty"`
	Bsize         uint32                 `protobuf:"varint,7,opt,name=bsize,proto3" json:"bsize,omitempty"`
	Frsize        uint32                 `protobuf:"varint,8,opt,name=frsize,proto3" json:"frsize,omitempty"`
	Namelen       uint32                 `protobuf:"varint,9,opt,name=namelen,proto3" json:"namelen,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatFsResponse) Reset() {
	*x = StatFsResponse{}
	mi := &file_proto_clibox_proto_msgTypes[47]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatFsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatFsResponse) ProtoMessage() {}

func (x *StatFsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[47]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatFsResponse.ProtoReflect.Descriptor instead.
func (*StatFsResponse) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{47}
}

func (x *StatFsResponse) GetErrno() int32 {
	if x != nil {
		return x.Errno
	}
	return 0
}

func (x *StatFsResponse) GetBlocks() uint64 {
	if x != nil {
		return x.Blocks
	}
	return 0
}

func (x *StatFsResponse) GetBfree() uint64 {
	if x != nil {
		return x.Bfree
	}
	return 0
}

func (x *StatFsResponse) GetBavail() uint64 {
	if x != nil {
		return x.Bavail
	}
	return 0
}

func (x *StatFsResponse) GetFiles() uint64 {
	if x != nil {
		return x.Files
	}
	return 0
}

func (x *StatFsResponse) GetFfree() uint64 {
	if x != nil {
		return x.Ffree
	}
	return 0
}

func (x *StatFsResponse) GetBsize() uint32 {
	if x != nil {
		return x.Bsize
	}
	return 0
}

func (x *StatFsResponse) GetFrsize() uint32 {
	if x != nil {
		return x.Frsize
	}
	return 0
}

func (x *StatFsResponse) GetNamelen() uint32 {
	if x != nil {
		return x.Namelen
	}
	return 0
}

type ExecInput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Input:
	//
	//	*ExecInput_Start
	//	*ExecInput_Stdin
	//	*ExecInput_Signal
	//	*ExecInput_Resize
	Input         isExecInput_Input `protobuf_oneof:"input"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecInput) Reset() {
	*x = ExecInput{}
	mi := &file_proto_clibox_proto_msgTypes[48]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecInput) ProtoMessage() {}

func (x *ExecInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[48]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecInput.ProtoReflect.Descriptor instead.
func (*ExecInput) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{48}
}

func (x *ExecInput) GetInput() isExecInput_Input {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ExecInput) GetStart() *ExecStart {
	if x != nil {
		if x, ok := x.Input.(*ExecInput_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *ExecInput) GetStdin() []byte {
	if x != nil {
		if x, ok := x.Input.(*ExecInput_Stdin); ok {
			return x.Stdin
		}
	}
	return nil
}

func (x *ExecInput) GetSignal() *Signal {
	if x != nil {
		if x, ok := x.Input.(*ExecInput_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

func (x *ExecInput) GetResize() *WindowSize {
	if x != nil {
		if x, ok := x.Input.(*ExecInput_Resize); ok {
			return x.Resize
		}
	}
	return nil
}

type isExecInput_Input interface {
	isExecInput_Input()
}

type ExecInput_Start struct {
	Start *ExecStart `protobuf:"bytes,1,opt,name=start,proto3,oneof"`
}

type ExecInput_Stdin struct {
	Stdin []byte `protobuf:"bytes,2,opt,name=stdin,proto3,oneof"`
}

type ExecInput_Signal struct {
	Signal *Signal `protobuf:"bytes,3,opt,name=signal,proto3,oneof"`
}

type ExecInput_Resize struct {
	Resize *WindowSize `protobuf:"bytes,4,opt,name=resize,proto3,oneof"`
}

func (*ExecInput_Start) isExecInput_Input() {}

func (*ExecInput_Stdin) isExecInput_Input() {}

func (*ExecInput_Signal) isExecInput_Input() {}

func (*ExecInput_Resize) isExecInput_Input() {}

type ExecOutput struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Output:
	//
	//	*ExecOutput_Stdout
	//	*ExecOutput_Stderr
	//	*ExecOutput_Exit
	Output        isExecOutput_Output `protobuf_oneof:"output"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecOutput) Reset() {
	*x = ExecOutput{}
	mi := &file_proto_clibox_proto_msgTypes[49]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecOutput) ProtoMessage() {}

func (x *ExecOutput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[49]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecOutput.ProtoReflect.Descriptor instead.
func (*ExecOutput) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{49}
}

func (x *ExecOutput) GetOutput() isExecOutput_Output {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ExecOutput) GetStdout() []byte {
	if x != nil {
		if x, ok := x.Output.(*ExecOutput_Stdout); ok {
			return x.Stdout
		}
	}
	return nil
}

func (x *ExecOutput) GetStderr() []byte {
	if x != nil {
		if x, ok := x.Output.(*ExecOutput_Stderr); ok {
			return x.Stderr
		}
	}
	return nil
}

func (x *ExecOutput) GetExit() *ExecExit {
	if x != nil {
		if x, ok := x.Output.(*ExecOutput_Exit); ok {
			return x.Exit
		}
	}
	return nil
}

type isExecOutput_Output interface {
	isExecOutput_Output()
}

type ExecOutput_Stdout struct {
	Stdout []byte `protobuf:"bytes,1,opt,name=stdout,proto3,oneof"`
}

type ExecOutput_Stderr struct {
	Stderr []byte `protobuf:"bytes,2,opt,name=stderr,proto3,oneof"`
}

type ExecOutput_Exit struct {
	Exit *ExecExit `protobuf:"bytes,3,opt,name=exit,proto3,oneof"`
}

func (*ExecOutput_Stdout) isExecOutput_Output() {}

func (*ExecOutput_Stderr) isExecOutput_Output() {}

func (*ExecOutput_Exit) isExecOutput_Output() {}

type ExecStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Env           map[string]string      `protobuf:"bytes,2,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Cwd           string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	Tty           bool                   `protobuf:"varint,4,opt,name=tty,proto3" json:"tty,omitempty"`
	WindowSize    *WindowSize            `protobuf:"bytes,5,opt,name=window_size,json=windowSize,proto3" json:"window_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecStart) Reset() {
	*x = ExecStart{}
	mi := &file_proto_clibox_proto_msgTypes[50]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecStart) ProtoMessage() {}

func (x *ExecStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[50]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecStart.ProtoReflect.Descriptor instead.
func (*ExecStart) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{50}
}

func (x *ExecStart) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ExecStart) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *ExecStart) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

func (x *ExecStart) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

func (x *ExecStart) GetWindowSize() *WindowSize {
	if x != nil {
		return x.WindowSize
	}
	return nil
}

type ExecExit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ExitCode      int32                  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecExit) Reset() {
	*x = ExecExit{}
	mi := &file_proto_clibox_proto_msgTypes[51]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecExit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecExit) ProtoMessage() {}

func (x *ExecExit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[51]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecExit.ProtoReflect.Descriptor instead.
func (*ExecExit) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{51}
}

func (x *ExecExit) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type Signal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signum        int32                  `protobuf:"varint,1,opt,name=signum,proto3" json:"signum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Signal) Reset() {
	*x = Signal{}
	mi := &file_proto_clibox_proto_msgTypes[52]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Signal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Signal) ProtoMessage() {}

func (x *Signal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[52]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Signal.ProtoReflect.Descriptor instead.
func (*Signal) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{52}
}

func (x *Signal) GetSignum() int32 {
	if x != nil {
		return x.Signum
	}
	return 0
}

type WindowSize struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          uint32                 `protobuf:"varint,1,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          uint32                 `protobuf:"varint,2,opt,name=cols,proto3" json:"cols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WindowSize) Reset() {
	*x = WindowSize{}
	mi := &file_proto_clibox_proto_msgTypes[53]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WindowSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WindowSize) ProtoMessage() {}

func (x *WindowSize) ProtoReflect() protoreflect.Message {
	mi := &file_proto_clibox_proto_msgTypes[53]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WindowSize.ProtoReflect.Descriptor instead.
func (*WindowSize) Descriptor() ([]byte, []int) {
	return file_proto_clibox_proto_rawDescGZIP(), []int{53}
}

func (x *WindowSize) GetRows() uint32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *WindowSize) GetCols() uint32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

var File_proto_clibox_proto protoreflect.FileDescriptor

const file_proto_clibox_proto_rawDesc = "" +
	"\n" +
	"\x12proto/clibox.proto\x12\x06clibox\"\xb2\x02\n" +
	"\bFileAttr\x12\x10\n" +
	"\x03ino\x18\x01 \x01(\x04R\x03ino\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\x12\x14\n" +
	"\x05nlink\x18\x04 \x01(\rR\x05nlink\x12\x10\n" +
	"\x03uid\x18\x05 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x06 \x01(\rR\x03gid\x12\x1b\n" +
	"\tatime_sec\x18\a \x01(\x03R\batimeSec\x12\x1b\n" +
	"\tmtime_sec\x18\b \x01(\x03R\bmtimeSec\x12\x1b\n" +
	"\tctime_sec\x18\t \x01(\x03R\bctimeSec\x12\x1d\n" +
	"\n" +
	"atime_nsec\x18\n" +
	" \x01(\x05R\tatimeNsec\x12\x1d\n" +
	"\n" +
	"mtime_nsec\x18\v \x01(\x05R\tmtimeNsec\x12\x1d\n" +
	"\n" +
	"ctime_nsec\x18\f \x01(\x05R\tctimeNsec\"D\n" +
	"\bDirEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03ino\x18\x02 \x01(\x04R\x03ino\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\rR\x04mode\"$\n" +
	"\x0eGetAttrRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"M\n" +
	"\x0fGetAttrResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12$\n" +
	"\x04attr\x18\x02 \x01(\v2\x10.clibox.FileAttrR\x04attr\";\n" +
	"\rLookupRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"L\n" +
	"\x0eLookupResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12$\n" +
	"\x04attr\x18\x02 \x01(\v2\x10.clibox.FileAttrR\x04attr\"%\n" +
	"\x0fReadLinkRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"@\n" +
	"\x10ReadLinkResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\"$\n" +
	"\x0eOpenDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"7\n" +
	"\x0fOpenDirResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12\x0e\n" +
	"\x02fh\x18\x02 \x01(\x04R\x02fh\"L\n" +
	"\x0eReadDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02fh\x18\x02 \x01(\x04R\x02fh\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x04R\x06offset\"S\n" +
	"\x0fReadDirResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12*\n" +
	"\aentries\x18\x02 \x03(\v2\x10.clibox.DirEntryR\aentries\"7\n" +
	"\x11ReleaseDirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02fh\x18\x02 \x01(\x04R\x02fh\"*\n" +
	"\x12ReleaseDirResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\"6\n" +
	"\fMkdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"K\n" +
	"\rMkdirResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12$\n" +
	"\x04attr\x18\x02 \x01(\v2\x10.clibox.FileAttrR\x04attr\"\"\n" +
	"\fRmdirRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"%\n" +
	"\rRmdirResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\"7\n" +
	"\vOpenRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x14\n" +
	"\x05flags\x18\x02 \x01(\rR\x05flags\"4\n" +
	"\fOpenResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12\x0e\n" +
	"\x02fh\x18\x02 \x01(\x04R\x02fh\"]\n" +
	"\vReadRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02fh\x18\x02 \x01(\x04R\x02fh\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\"8\n" +
	"\fReadResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"^\n" +
	"\fWriteRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02fh\x18\x02 \x01(\x04R\x02fh\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x03R\x06offset\x12\x12\n" +
	"\x04data\x18\x04 \x01(\fR\x04data\"?\n" +
	"\rWriteResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12\x18\n" +
	"\awritten\x18\x02 \x01(\rR\awritten\"4\n" +
	"\x0eReleaseRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02fh\x18\x02 \x01(\x04R\x02fh\"'\n" +
	"\x0fReleaseResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\"M\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\x12\x14\n" +
	"\x05flags\x18\x03 \x01(\rR\x05flags\"\\\n" +
	"\x0eCreateResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12\x0e\n" +
	"\x02fh\x18\x02 \x01(\x04R\x02fh\x12$\n" +
	"\x04attr\x18\x03 \x01(\v2\x10.clibox.FileAttrR\x04attr\"#\n" +
	"\rUnlinkRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"&\n" +
	"\x0eUnlinkResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\"E\n" +
	"\rRenameRequest\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\"&\n" +
	"\x0eRenameResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\"9\n" +
	"\x0fTruncateRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x03R\x04size\"(\n" +
	"\x10TruncateResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\"6\n" +
	"\fChmodRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\rR\x04mode\"%\n" +
	"\rChmodResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\"F\n" +
	"\fChownRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x10\n" +
	"\x03uid\x18\x02 \x01(\rR\x03uid\x12\x10\n" +
	"\x03gid\x18\x03 \x01(\rR\x03gid\"%\n" +
	"\rChownResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\"\x9c\x01\n" +
	"\x0eUtimensRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1b\n" +
	"\tatime_sec\x18\x02 \x01(\x03R\batimeSec\x12\x1d\n" +
	"\n" +
	"atime_nsec\x18\x03 \x01(\x05R\tatimeNsec\x12\x1b\n" +
	"\tmtime_sec\x18\x04 \x01(\x03R\bmtimeSec\x12\x1d\n" +
	"\n" +
	"mtime_nsec\x18\x05 \x01(\x05R\tmtimeNsec\"'\n" +
	"\x0fUtimensResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\"E\n" +
	"\x0eSymlinkRequest\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12\x1b\n" +
	"\tlink_path\x18\x02 \x01(\tR\blinkPath\"M\n" +
	"\x0fSymlinkResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12$\n" +
	"\x04attr\x18\x02 \x01(\v2\x10.clibox.FileAttrR\x04attr\"C\n" +
	"\vLinkRequest\x12\x19\n" +
	"\bold_path\x18\x01 \x01(\tR\aoldPath\x12\x19\n" +
	"\bnew_path\x18\x02 \x01(\tR\anewPath\"J\n" +
	"\fLinkResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12$\n" +
	"\x04attr\x18\x02 \x01(\v2\x10.clibox.FileAttrR\x04attr\"N\n" +
	"\fFsyncRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x0e\n" +
	"\x02fh\x18\x02 \x01(\x04R\x02fh\x12\x1a\n" +
	"\bdatasync\x18\x03 \x01(\bR\bdatasync\"%\n" +
	"\rFsyncResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\"#\n" +
	"\rStatFsRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\"\xe0\x01\n" +
	"\x0eStatFsResponse\x12\x14\n" +
	"\x05errno\x18\x01 \x01(\x05R\x05errno\x12\x16\n" +
	"\x06blocks\x18\x02 \x01(\x04R\x06blocks\x12\x14\n" +
	"\x05bfree\x18\x03 \x01(\x04R\x05bfree\x12\x16\n" +
	"\x06bavail\x18\x04 \x01(\x04R\x06bavail\x12\x14\n" +
	"\x05files\x18\x05 \x01(\x04R\x05files\x12\x14\n" +
	"\x05ffree\x18\x06 \x01(\x04R\x05ffree\x12\x14\n" +
	"\x05bsize\x18\a \x01(\rR\x05bsize\x12\x16\n" +
	"\x06frsize\x18\b \x01(\rR\x06frsize\x12\x18\n" +
	"\anamelen\x18\t \x01(\rR\anamelen\"\xaf\x01\n" +
	"\tExecInput\x12)\n" +
	"\x05start\x18\x01 \x01(\v2\x11.clibox.ExecStartH\x00R\x05start\x12\x16\n" +
	"\x05stdin\x18\x02 \x01(\fH\x00R\x05stdin\x12(\n" +
	"\x06signal\x18\x03 \x01(\v2\x0e.clibox.SignalH\x00R\x06signal\x12,\n" +
	"\x06resize\x18\x04 \x01(\v2\x12.clibox.WindowSizeH\x00R\x06resizeB\a\n" +
	"\x05input\"r\n" +
	"\n" +
	"ExecOutput\x12\x18\n" +
	"\x06stdout\x18\x01 \x01(\fH\x00R\x06stdout\x12\x18\n" +
	"\x06stderr\x18\x02 \x01(\fH\x00R\x06stderr\x12&\n" +
	"\x04exit\x18\x03 \x01(\v2\x10.clibox.ExecExitH\x00R\x04exitB\b\n" +
	"\x06output\"\xde\x01\n" +
	"\tExecStart\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\x12,\n" +
	"\x03env\x18\x02 \x03(\v2\x1a.clibox.ExecStart.EnvEntryR\x03env\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\x12\x10\n" +
	"\x03tty\x18\x04 \x01(\bR\x03tty\x123\n" +
	"\vwindow_size\x18\x05 \x01(\v2\x12.clibox.WindowSizeR\n" +
	"windowSize\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"'\n" +
	"\bExecExit\x12\x1b\n" +
	"\texit_code\x18\x01 \x01(\x05R\bexitCode\" \n" +
	"\x06Signal\x12\x16\n" +
	"\x06signum\x18\x01 \x01(\x05R\x06signum\"4\n" +
	"\n" +
	"WindowSize\x12\x12\n" +
	"\x04rows\x18\x01 \x01(\rR\x04rows\x12\x12\n" +
	"\x04cols\x18\x02 \x01(\rR\x04cols2\xb1\n" +
	"\n" +
	"\n" +
	"FileSystem\x12:\n" +
	"\aGetAttr\x12\x16.clibox.GetAttrRequest\x1a\x17.clibox.GetAttrResponse\x127\n" +
	"\x06Lookup\x12\x15.clibox.LookupRequest\x1a\x16.clibox.LookupResponse\x12=\n" +
	"\bReadLink\x12\x17.clibox.ReadLinkRequest\x1a\x18.clibox.ReadLinkResponse\x12:\n" +
	"\aOpenDir\x12\x16.clibox.OpenDirRequest\x1a\x17.clibox.OpenDirResponse\x12:\n" +
	"\aReadDir\x12\x16.clibox.ReadDirRequest\x1a\x17.clibox.ReadDirResponse\x12C\n" +
	"\n" +
	"ReleaseDir\x12\x19.clibox.ReleaseDirRequest\x1a\x1a.clibox.ReleaseDirResponse\x124\n" +
	"\x05Mkdir\x12\x14.clibox.MkdirRequest\x1a\x15.clibox.MkdirResponse\x124\n" +
	"\x05Rmdir\x12\x14.clibox.RmdirRequest\x1a\x15.clibox.RmdirResponse\x121\n" +
	"\x04Open\x12\x13.clibox.OpenRequest\x1a\x14.clibox.OpenResponse\x121\n" +
	"\x04Read\x12\x13.clibox.ReadRequest\x1a\x14.clibox.ReadResponse\x124\n" +
	"\x05Write\x12\x14.clibox.WriteRequest\x1a\x15.clibox.WriteResponse\x12:\n" +
	"\aRelease\x12\x16.clibox.ReleaseRequest\x1a\x17.clibox.ReleaseResponse\x127\n" +
	"\x06Create\x12\x15.clibox.CreateRequest\x1a\x16.clibox.CreateResponse\x127\n" +
	"\x06Unlink\x12\x15.clibox.UnlinkRequest\x1a\x16.clibox.UnlinkResponse\x127\n" +
	"\x06Rename\x12\x15.clibox.RenameRequest\x1a\x16.clibox.RenameResponse\x12=\n" +
	"\bTruncate\x12\x17.clibox.TruncateRequest\x1a\x18.clibox.TruncateResponse\x124\n" +
	"\x05Chmod\x12\x14.clibox.ChmodRequest\x1a\x15.clibox.ChmodResponse\x124\n" +
	"\x05Chown\x12\x14.clibox.ChownRequest\x1a\x15.clibox.ChownResponse\x12:\n" +
	"\aUtimens\x12\x16.clibox.UtimensRequest\x1a\x17.clibox.UtimensResponse\x12:\n" +
	"\aSymlink\x12\x16.clibox.SymlinkRequest\x1a\x17.clibox.SymlinkResponse\x121\n" +
	"\x04Link\x12\x13.clibox.LinkRequest\x1a\x14.clibox.LinkResponse\x124\n" +
	"\x05Fsync\x12\x14.clibox.FsyncRequest\x1a\x15.clibox.FsyncResponse\x127\n" +
	"\x06StatFs\x12\x15.clibox.StatFsRequest\x1a\x16.clibox.StatFsResponse2<\n" +
	"\aCommand\x121\n" +
	"\x04Exec\x12\x11.clibox.ExecInput\x1a\x12.clibox.ExecOutput(\x010\x01B#Z!github.com/cli-auth/cli-box/protob\x06proto3"

var (
	file_proto_clibox_proto_rawDescOnce sync.Once
	file_proto_clibox_proto_rawDescData []byte
)

func file_proto_clibox_proto_rawDescGZIP() []byte {
	file_proto_clibox_proto_rawDescOnce.Do(func() {
		file_proto_clibox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_clibox_proto_rawDesc), len(file_proto_clibox_proto_rawDesc)))
	})
	return file_proto_clibox_proto_rawDescData
}

var file_proto_clibox_proto_msgTypes = make([]protoimpl.MessageInfo, 55)
var file_proto_clibox_proto_goTypes = []any{
	(*FileAttr)(nil),           // 0: clibox.FileAttr
	(*DirEntry)(nil),           // 1: clibox.DirEntry
	(*GetAttrRequest)(nil),     // 2: clibox.GetAttrRequest
	(*GetAttrResponse)(nil),    // 3: clibox.GetAttrResponse
	(*LookupRequest)(nil),      // 4: clibox.LookupRequest
	(*LookupResponse)(nil),     // 5: clibox.LookupResponse
	(*ReadLinkRequest)(nil),    // 6: clibox.ReadLinkRequest
	(*ReadLinkResponse)(nil),   // 7: clibox.ReadLinkResponse
	(*OpenDirRequest)(nil),     // 8: clibox.OpenDirRequest
	(*OpenDirResponse)(nil),    // 9: clibox.OpenDirResponse
	(*ReadDirRequest)(nil),     // 10: clibox.ReadDirRequest
	(*ReadDirResponse)(nil),    // 11: clibox.ReadDirResponse
	(*ReleaseDirRequest)(nil),  // 12: clibox.ReleaseDirRequest
	(*ReleaseDirResponse)(nil), // 13: clibox.ReleaseDirResponse
	(*MkdirRequest)(nil),       // 14: clibox.MkdirRequest
	(*MkdirResponse)(nil),      // 15: clibox.MkdirResponse
	(*RmdirRequest)(nil),       // 16: clibox.RmdirRequest
	(*RmdirResponse)(nil),      // 17: clibox.RmdirResponse
	(*OpenRequest)(nil),        // 18: clibox.OpenRequest
	(*OpenResponse)(nil),       // 19: clibox.OpenResponse
	(*ReadRequest)(nil),        // 20: clibox.ReadRequest
	(*ReadResponse)(nil),       // 21: clibox.ReadResponse
	(*WriteRequest)(nil),       // 22: clibox.WriteRequest
	(*WriteResponse)(nil),      // 23: clibox.WriteResponse
	(*ReleaseRequest)(nil),     // 24: clibox.ReleaseRequest
	(*ReleaseResponse)(nil),    // 25: clibox.ReleaseResponse
	(*CreateRequest)(nil),      // 26: clibox.CreateRequest
	(*CreateResponse)(nil),     // 27: clibox.CreateResponse
	(*UnlinkRequest)(nil),      // 28: clibox.UnlinkRequest
	(*UnlinkResponse)(nil),     // 29: clibox.UnlinkResponse
	(*RenameRequest)(nil),      // 30: clibox.RenameRequest
	(*RenameResponse)(nil),     // 31: clibox.RenameResponse
	(*TruncateRequest)(nil),    // 32: clibox.TruncateRequest
	(*TruncateResponse)(nil),   // 33: clibox.TruncateResponse
	(*ChmodRequest)(nil),       // 34: clibox.ChmodRequest
	(*ChmodResponse)(nil),      // 35: clibox.ChmodResponse
	(*ChownRequest)(nil),       // 36: clibox.ChownRequest
	(*ChownResponse)(nil),      // 37: clibox.ChownResponse
	(*UtimensRequest)(nil),     // 38: clibox.UtimensRequest
	(*UtimensResponse)(nil),    // 39: clibox.UtimensResponse
	(*SymlinkRequest)(nil),     // 40: clibox.SymlinkRequest
	(*SymlinkResponse)(nil),    // 41: clibox.SymlinkResponse
	(*LinkRequest)(nil),        // 42: clibox.LinkRequest
	(*LinkResponse)(nil),       // 43: clibox.LinkResponse
	(*FsyncRequest)(nil),       // 44: clibox.FsyncRequest
	(*FsyncResponse)(nil),      // 45: clibox.FsyncResponse
	(*StatFsRequest)(nil),      // 46: clibox.StatFsRequest
	(*StatFsResponse)(nil),     // 47: clibox.StatFsResponse
	(*ExecInput)(nil),          // 48: clibox.ExecInput
	(*ExecOutput)(nil),         // 49: clibox.ExecOutput
	(*ExecStart)(nil),          // 50: clibox.ExecStart
	(*ExecExit)(nil),           // 51: clibox.ExecExit
	(*Signal)(nil),             // 52: clibox.Signal
	(*WindowSize)(nil),         // 53: clibox.WindowSize
	nil,                        // 54: clibox.ExecStart.EnvEntry
}
var file_proto_clibox_proto_depIdxs = []int32{
	0,  // 0: clibox.GetAttrResponse.attr:type_name -> clibox.FileAttr
	0,  // 1: clibox.LookupResponse.attr:type_name -> clibox.FileAttr
	1,  // 2: clibox.ReadDirResponse.entries:type_name -> clibox.DirEntry
	0,  // 3: clibox.MkdirResponse.attr:type_name -> clibox.FileAttr
	0,  // 4: clibox.CreateResponse.attr:type_name -> clibox.FileAttr
	0,  // 5: clibox.SymlinkResponse.attr:type_name -> clibox.FileAttr
	0,  // 6: clibox.LinkResponse.attr:type_name -> clibox.FileAttr
	50, // 7: clibox.ExecInput.start:type_name -> clibox.ExecStart
	52, // 8: clibox.ExecInput.signal:type_name -> clibox.Signal
	53, // 9: clibox.ExecInput.resize:type_name -> clibox.WindowSize
	51, // 10: clibox.ExecOutput.exit:type_name -> clibox.ExecExit
	54, // 11: clibox.ExecStart.env:type_name -> clibox.ExecStart.EnvEntry
	53, // 12: clibox.ExecStart.window_size:type_name -> clibox.WindowSize
	2,  // 13: clibox.FileSystem.GetAttr:input_type -> clibox.GetAttrRequest
	4,  // 14: clibox.FileSystem.Lookup:input_type -> clibox.LookupRequest
	6,  // 15: clibox.FileSystem.ReadLink:input_type -> clibox.ReadLinkRequest
	8,  // 16: clibox.FileSystem.OpenDir:input_type -> clibox.OpenDirRequest
	10, // 17: clibox.FileSystem.ReadDir:input_type -> clibox.ReadDirRequest
	12, // 18: clibox.FileSystem.ReleaseDir:input_type -> clibox.ReleaseDirRequest
	14, // 19: clibox.FileSystem.Mkdir:input_type -> clibox.MkdirRequest
	16, // 20: clibox.FileSystem.Rmdir:input_type -> clibox.RmdirRequest
	18, // 21: clibox.FileSystem.Open:input_type -> clibox.OpenRequest
	20, // 22: clibox.FileSystem.Read:input_type -> clibox.ReadRequest
	22, // 23: clibox.FileSystem.Write:input_type -> clibox.WriteRequest
	24, // 24: clibox.FileSystem.Release:input_type -> clibox.ReleaseRequest
	26, // 25: clibox.FileSystem.Create:input_type -> clibox.CreateRequest
	28, // 26: clibox.FileSystem.Unlink:input_type -> clibox.UnlinkRequest
	30, // 27: clibox.FileSystem.Rename:input_type -> clibox.RenameRequest
	32, // 28: clibox.FileSystem.Truncate:input_type -> clibox.TruncateRequest
	34, // 29: clibox.FileSystem.Chmod:input_type -> clibox.ChmodRequest
	36, // 30: clibox.FileSystem.Chown:input_type -> clibox.ChownRequest
	38, // 31: clibox.FileSystem.Utimens:input_type -> clibox.UtimensRequest
	40, // 32: clibox.FileSystem.Symlink:input_type -> clibox.SymlinkRequest
	42, // 33: clibox.FileSystem.Link:input_type -> clibox.LinkRequest
	44, // 34: clibox.FileSystem.Fsync:input_type -> clibox.FsyncRequest
	46, // 35: clibox.FileSystem.StatFs:input_type -> clibox.StatFsRequest
	48, // 36: clibox.Command.Exec:input_type -> clibox.ExecInput
	3,  // 37: clibox.FileSystem.GetAttr:output_type -> clibox.GetAttrResponse
	5,  // 38: clibox.FileSystem.Lookup:output_type -> clibox.LookupResponse
	7,  // 39: clibox.FileSystem.ReadLink:output_type -> clibox.ReadLinkResponse
	9,  // 40: clibox.FileSystem.OpenDir:output_type -> clibox.OpenDirResponse
	11, // 41: clibox.FileSystem.ReadDir:output_type -> clibox.ReadDirResponse
	13, // 42: clibox.FileSystem.ReleaseDir:output_type -> clibox.ReleaseDirResponse
	15, // 43: clibox.FileSystem.Mkdir:output_type -> clibox.MkdirResponse
	17, // 44: clibox.FileSystem.Rmdir:output_type -> clibox.RmdirResponse
	19, // 45: clibox.FileSystem.Open:output_type -> clibox.OpenResponse
	21, // 46: clibox.FileSystem.Read:output_type -> clibox.ReadResponse
	23, // 47: clibox.FileSystem.Write:output_type -> clibox.WriteResponse
	25, // 48: clibox.FileSystem.Release:output_type -> clibox.ReleaseResponse
	27, // 49: clibox.FileSystem.Create:output_type -> clibox.CreateResponse
	29, // 50: clibox.FileSystem.Unlink:output_type -> clibox.UnlinkResponse
	31, // 51: clibox.FileSystem.Rename:output_type -> clibox.RenameResponse
	33, // 52: clibox.FileSystem.Truncate:output_type -> clibox.TruncateResponse
	35, // 53: clibox.FileSystem.Chmod:output_type -> clibox.ChmodResponse
	37, // 54: clibox.FileSystem.Chown:output_type -> clibox.ChownResponse
	39, // 55: clibox.FileSystem.Utimens:output_type -> clibox.UtimensResponse
	41, // 56: clibox.FileSystem.Symlink:output_type -> clibox.SymlinkResponse
	43, // 57: clibox.FileSystem.Link:output_type -> clibox.LinkResponse
	45, // 58: clibox.FileSystem.Fsync:output_type -> clibox.FsyncResponse
	47, // 59: clibox.FileSystem.StatFs:output_type -> clibox.StatFsResponse
	49, // 60: clibox.Command.Exec:output_type -> clibox.ExecOutput
	37, // [37:61] is the sub-list for method output_type
	13, // [13:37] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_clibox_proto_init() }
func file_proto_clibox_proto_init() {
	if File_proto_clibox_proto != nil {
		return
	}
	file_proto_clibox_proto_msgTypes[48].OneofWrappers = []any{
		(*ExecInput_Start)(nil),
		(*ExecInput_Stdin)(nil),
		(*ExecInput_Signal)(nil),
		(*ExecInput_Resize)(nil),
	}
	file_proto_clibox_proto_msgTypes[49].OneofWrappers = []any{
		(*ExecOutput_Stdout)(nil),
		(*ExecOutput_Stderr)(nil),
		(*ExecOutput_Exit)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_clibox_proto_rawDesc), len(file_proto_clibox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   55,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_clibox_proto_goTypes,
		DependencyIndexes: file_proto_clibox_proto_depIdxs,
		MessageInfos:      file_proto_clibox_proto_msgTypes,
	}.Build()
	File_proto_clibox_proto = out.File
	file_proto_clibox_proto_goTypes = nil
	file_proto_clibox_proto_depIdxs = nil
}
